# Generated by Django 4.2.2 on 2023-06-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
